name: Promote Image to registry.k8s.io

on:
  schedule:
    - cron: '0 16 * * *' # Run every day at GMT+8 midnight

  workflow_dispatch: # Use for manaully trigger to debug

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # This step uses Github's checkout-action: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run kpromo command to promote image to registry.k8s.io
        run: |
          ./hack/kpromo.sh
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
